### ISSUE TITLE
"Currently uploading" could have a percentage for each file

### ISSUE THREAD

**Issue by leijurv** [leijurv/gb#33]
Could put something between the open file and the compressor that records the quantity of bytes read, and compares it to the expected size from stat-ing the file.

<img width="964" alt="Screen Shot 2023-02-05 at 10 21 16 PM" src="https://user-images.githubusercontent.com/3837873/216897932-48af8bfa-ef63-4088-89ea-7d8de4c106f8.png">

something like this could be cool.

Then gb would actually be able to report what percent done it is instead of just `Currently uploading: /path/to/some/huge/linux.iso` over and over and you having no idea how much progress it's made through that file

**Comment by 5HT2** [comment]
> Could put something between the open file and the compressor that records the quantity of bytes read, and compares it to the expected size from stat-ing the file.

There's an io.Writer or io.Reader, right? You can use something like https://github.com/schollz/progressbar/ to have a progress bar
